In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
reproduciblity = True
if reproduciblity:
    random.seed(10)

In [ ]:
m4s = ["Daily", "Hourly", "Weekly"]
M4_TYPE = m4s[2]

df_train = pd.read_csv(f"Dataset/M4/{M4_TYPE}-train.csv")
df_test = pd.read_csv(f"Dataset/M4/{M4_TYPE}-test.csv")

In [20]:

data_arr = df_train.iloc[:, 1:].values
data_arr = list(data_arr)
for i, ts in enumerate(data_arr):
    data_arr[i] = ts[~np.isnan(ts)][None, :]

In [21]:
df_test

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
0,W1,35397.160,35808.590,35808.59,36246.140,36246.140,36403.700,36403.700,36150.20,36150.200,35790.550,35790.550,34066.950,34066.950
1,W2,3608.061,3624.368,3537.64,3587.344,3662.088,3658.634,3622.148,3591.48,3638.559,3635.781,3522.328,3458.631,3354.758
2,W3,9602.400,9895.900,9915.90,9726.600,9626.500,9966.100,10008.500,9911.70,9760.700,9968.200,10089.100,10005.900,9823.300
3,W4,2336.560,2373.140,2457.51,2586.000,2237.700,2877.940,2497.740,3525.34,3053.330,3151.070,3425.790,3505.610,4098.690
4,W5,1499.000,1734.000,1391.00,1833.000,1637.000,2122.000,1757.000,2079.00,2477.000,1957.000,1907.000,1752.000,1330.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,W355,2777.000,2893.000,2760.00,2745.000,2807.000,2862.000,2880.000,2838.00,2908.000,2838.000,2698.000,3357.000,2928.000
355,W356,4387.000,3772.000,3660.00,3878.000,3131.000,2405.000,4081.000,4811.00,4170.000,4017.000,3824.000,4661.000,4297.000
356,W357,3938.000,3363.000,3249.00,3515.000,3097.000,2275.000,3421.000,4166.00,3807.000,3434.000,3303.000,4024.000,3747.000
357,W358,6907.000,5711.000,5496.00,5862.000,5380.000,3660.000,5159.000,6787.00,5596.000,5445.000,5345.000,6156.000,5866.000
358,W359,4458.000,5098.000,4518.00,4973.000,3973.000,2613.000,3476.000,4213.00,3386.000,3627.000,3299.000,3743.000,3965.000

In [14]:
df_test.shape[1]

49

In [12]:
def give_indexes(df_train):
    data_arr = df_train.iloc[:, 1:].values
    data_arr = list(data_arr)
    for i, ts in enumerate(data_arr):
        data_arr[i] = ts[~np.isnan(ts)][None, :]
    indexes = []
    for ind in range(len(data_arr)):
        if data_arr[ind].shape[1] > 500:
            indexes.append(ind)
    return indexes

In [13]:
indexes = give_indexes(df_train)

In [14]:
len(indexes)

252

In [15]:
random.seed(10)
randomlist = random.sample(indexes, 252)
randomlist

[170,
 8,
 130,
 146,
 171,
 3,
 53,
 141,
 239,
 148,
 241,
 79,
 195,
 238,
 42,
 292,
 156,
 284,
 96,
 20,
 66,
 221,
 107,
 12,
 127,
 251,
 36,
 180,
 105,
 114,
 258,
 80,
 242,
 200,
 74,
 139,
 45,
 203,
 88,
 197,
 260,
 35,
 247,
 227,
 64,
 133,
 184,
 113,
 259,
 174,
 1,
 63,
 283,
 50,
 244,
 160,
 108,
 280,
 91,
 198,
 164,
 138,
 132,
 143,
 17,
 281,
 233,
 272,
 151,
 41,
 60,
 124,
 225,
 9,
 278,
 150,
 228,
 182,
 196,
 19,
 159,
 21,
 39,
 115,
 169,
 112,
 179,
 243,
 29,
 25,
 136,
 43,
 49,
 104,
 131,
 126,
 137,
 65,
 78,
 37,
 276,
 46,
 31,
 76,
 240,
 245,
 188,
 246,
 175,
 145,
 102,
 212,
 220,
 209,
 232,
 234,
 97,
 92,
 255,
 223,
 248,
 202,
 122,
 210,
 116,
 140,
 163,
 269,
 99,
 153,
 213,
 111,
 154,
 289,
 230,
 73,
 207,
 293,
 147,
 205,
 22,
 176,
 290,
 62,
 52,
 18,
 54,
 77,
 84,
 168,
 172,
 229,
 236,
 186,
 274,
 282,
 59,
 13,
 208,
 4,
 0,
 194,
 120,
 237,
 6,
 121,
 199,
 270,
 14,
 166,
 61,
 204,
 183,
 157,
 57,
 67,
 161,
 44,
 34,
 89,
 55,
 214,
 286,
 123,
 158,
 144,
 279,
 250,
 26,
 68,
 85,
 38,
 178,
 226,
 211,
 201,
 285,
 252,
 7,
 249,
 28,
 16,
 167,
 287,
 5,
 2,
 192,
 256,
 101,
 187,
 10,
 254,
 206,
 24,
 189,
 218,
 23,
 98,
 48,
 129,
 235,
 152,
 288,
 253,
 40,
 15,
 117,
 190,
 291,
 215,
 222,
 27,
 90,
 261,
 165,
 149,
 30,
 224,
 33,
 155,
 106,
 51,
 193,
 32,
 142,
 257,
 81,
 95,
 231,
 87,
 191,
 47]

In [16]:
train_series = df_train.iloc[randomlist,:]
test_series = df_test.iloc[randomlist,:]

In [17]:
train_series

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V2589,V2590,V2591,V2592,V2593,V2594,V2595,V2596,V2597,V2598
170,W171,4004.013000,4049.327000,4023.67600,3991.947000,3971.506000,3989.967000,4025.326000,3971.877000,3938.137000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,W9,9643.000000,10243.000000,10935.00000,9798.000000,9179.000000,8966.000000,8795.000000,8640.000000,11733.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,W131,1394.430000,1408.524000,1403.63300,1397.787000,1393.827000,1400.200000,1412.295000,1400.376000,1394.153000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,W147,935.126000,942.694000,895.75100,794.124000,826.761000,897.716000,925.921000,836.094000,777.677000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,W172,357.739700,342.903500,344.88270,340.719300,346.406800,338.934800,346.316700,350.008600,352.268100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,W96,613.674000,596.582000,597.56700,589.744000,596.468000,589.673000,598.109000,602.922000,605.118000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,W232,6134.000000,6082.900000,6058.20000,5986.900000,5834.500000,5662.700000,5189.300000,5134.200000,4725.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,W88,872.260000,850.030000,841.95000,831.160000,847.920000,850.020000,856.810000,866.120000,871.310000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,W192,1317.203331,1331.362533,1290.67206,1334.779396,1348.800103,1388.186102,1386.867837,1419.012995,1331.758745,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,W48,821.720000,818.380000,817.69000,817.875000,815.190000,819.680000,819.700000,818.700000,818.460000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
sum(train_series.index == test_series.index) == len(train_series)

True

In [19]:
train_series

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V2589,V2590,V2591,V2592,V2593,V2594,V2595,V2596,V2597,V2598
170,W171,4004.013000,4049.327000,4023.67600,3991.947000,3971.506000,3989.967000,4025.326000,3971.877000,3938.137000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,W9,9643.000000,10243.000000,10935.00000,9798.000000,9179.000000,8966.000000,8795.000000,8640.000000,11733.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,W131,1394.430000,1408.524000,1403.63300,1397.787000,1393.827000,1400.200000,1412.295000,1400.376000,1394.153000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,W147,935.126000,942.694000,895.75100,794.124000,826.761000,897.716000,925.921000,836.094000,777.677000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,W172,357.739700,342.903500,344.88270,340.719300,346.406800,338.934800,346.316700,350.008600,352.268100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,W96,613.674000,596.582000,597.56700,589.744000,596.468000,589.673000,598.109000,602.922000,605.118000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,W232,6134.000000,6082.900000,6058.20000,5986.900000,5834.500000,5662.700000,5189.300000,5134.200000,4725.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,W88,872.260000,850.030000,841.95000,831.160000,847.920000,850.020000,856.810000,866.120000,871.310000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,W192,1317.203331,1331.362533,1290.67206,1334.779396,1348.800103,1388.186102,1386.867837,1419.012995,1331.758745,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,W48,821.720000,818.380000,817.69000,817.875000,815.190000,819.680000,819.700000,818.700000,818.460000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
M4_TYPE

'Weekly'

In [21]:
def feature_extractor(data):
    data.loc[:,"y-1"] = data.loc[:,"y"].shift(1)
    data.loc[:,"y-2"] = data.loc[:,"y"].shift(2)
    data.loc[:,"y-3"] = data.loc[:,"y"].shift(3)
    
    if M4_TYPE == "Hourly":
        data.loc[:,"y-24"] = data.loc[:,"y"].shift(24)
        data.loc[:,"y-36"] = data.loc[:,"y"].shift(36)
        data.loc[:,"y-48"] = data.loc[:,"y"].shift(48)
        
        
        data.loc[:,"y-1_rolling_mean_4"] = data.loc[:,"y-1"].rolling(4).mean()
        data.loc[:,"y-1_rolling_std_4"] = data.loc[:,"y-1"].rolling(4).std()

        data.loc[:,"y-1_rolling_mean_7"] = data.loc[:,"y-1"].rolling(12).mean()
        data.loc[:,"y-1_rolling_std_7"] = data.loc[:,"y-1"].rolling(12).std()

        data.loc[:,"y-1_rolling_mean_28"] = data.loc[:,"y-1"].rolling(24).mean()
        data.loc[:,"y-1_rolling_std_28"] = data.loc[:,"y-1"].rolling(24).std()
        
        
        data.loc[:,"y-24_rolling_mean_4"] = data.loc[:,"y-24"].rolling(4).mean()
        data.loc[:,"y-24_rolling_std_4"] = data.loc[:,"y-24"].rolling(4).std()

        data.loc[:,"y-24_rolling_mean_7"] = data.loc[:,"y-24"].rolling(12).mean()
        data.loc[:,"y-24_rolling_std_7"] = data.loc[:,"y-24"].rolling(12).std()

        data.loc[:,"y-24_rolling_mean_28"] = data.loc[:,"y-24"].rolling(24).mean()
        data.loc[:,"y-24_rolling_std_28"] = data.loc[:,"y-24"].rolling(24).std()
        
        
        
    if M4_TYPE == "Weekly":
    
        data.loc[:,"y-4"] = data.loc[:,"y"].shift(4)
        data.loc[:,"y-52"] = data.loc[:,"y"].shift(52)
        #data.loc[:,"y-104"] = data.loc[:,"y"].shift(104)
        
        
        data.loc[:,"y-1_rolling_mean_4"] = data.loc[:,"y-1"].rolling(4).mean()
        data.loc[:,"y-1_rolling_std_4"] = data.loc[:,"y-1"].rolling(4).std()

        data.loc[:,"y-1_rolling_mean_12"] = data.loc[:,"y-1"].rolling(12).mean()
        data.loc[:,"y-1_rolling_std_12"] = data.loc[:,"y-1"].rolling(12).std()
        
        

    if M4_TYPE == "Daily":
        data.loc[:,"y-7"] = data.loc[:,"y"].shift(7)
        data.loc[:,"y-14"] = data.loc[:,"y"].shift(14)
        data.loc[:,"y-28"] = data.loc[:,"y"].shift(28)
        
    
        data.loc[:,"y-1_rolling_mean_4"] = data.loc[:,"y-1"].rolling(4).mean()
        data.loc[:,"y-1_rolling_std_4"] = data.loc[:,"y-1"].rolling(4).std()

        data.loc[:,"y-1_rolling_mean_7"] = data.loc[:,"y-1"].rolling(7).mean()
        data.loc[:,"y-1_rolling_std_7"] = data.loc[:,"y-1"].rolling(7).std()

        data.loc[:,"y-1_rolling_mean_28"] = data.loc[:,"y-1"].rolling(28).mean()
        data.loc[:,"y-1_rolling_std_28"] = data.loc[:,"y-1"].rolling(28).std()
        
        
        data.loc[:,"y-2_rolling_mean_4"] = data.loc[:,"y-2"].rolling(4).mean()
        data.loc[:,"y-2_rolling_std_4"] = data.loc[:,"y-2"].rolling(4).std()

        data.loc[:,"y-2_rolling_mean_7"] = data.loc[:,"y-2"].rolling(7).mean()
        data.loc[:,"y-2_rolling_std_7"] = data.loc[:,"y-2"].rolling(7).std()

        data.loc[:,"y-2_rolling_mean_28"] = data.loc[:,"y-2"].rolling(28).mean()
        data.loc[:,"y-2_rolling_std_28"] = data.loc[:,"y-2"].rolling(28).std()
        


    
    data = data.dropna()
    
    data.index = np.arange(len(data))
    return data

In [22]:
test_series

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14
170,W171,6104.414000,6112.220000,6095.080000,6100.620000,6117.270000,6120.080000,6088.190000,6084.550000,6119.760000,6132.760000,6176.580000,6188.090000,6213.000000
8,W9,8100.000000,7481.000000,8953.000000,8087.000000,9724.000000,8993.000000,10011.000000,9705.000000,8397.000000,7560.000000,8669.000000,7574.000000,7106.000000
130,W131,2161.865000,2166.713000,2152.117000,2152.923000,2163.772000,2170.279000,2156.830000,2153.923000,2159.431000,2164.374000,2153.369000,2154.844000,2158.018000
146,W147,120.660000,117.590000,111.320000,110.660000,110.460000,111.680000,120.320000,117.410000,125.320000,121.240000,112.520000,122.990000,118.270000
171,W172,3664.429800,3669.803000,3665.560000,3665.696000,3686.830000,3703.802000,3713.862000,3705.416000,3721.620000,3729.826000,3737.010000,3730.028000,3737.606000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,W96,11355.272000,11385.864000,11303.634000,11309.627000,11397.101000,11427.142000,11459.310000,11388.745000,11451.752000,11478.884000,11545.812000,11497.115000,11568.007000
231,W232,1880.400000,1889.200000,1864.500000,1961.100000,2009.700000,2211.100000,2235.000000,2421.800000,2774.000000,3052.000000,3018.400000,3171.400000,3206.100000
87,W88,12154.010000,12042.040000,12027.430000,11998.810000,12089.790000,12025.850000,12079.760000,12053.180000,12179.340000,12133.800000,12093.140000,12163.750000,12117.780000
191,W192,1160.330918,1165.783708,1130.218848,1144.012678,1116.237318,1143.744038,1056.720308,1119.294178,1064.618758,1048.372548,1135.591008,1105.256478,1120.579848
47,W48,2964.555000,2996.025000,3000.705000,2941.080000,2935.960000,2938.240000,2936.720000,2936.660000,2882.200000,2862.630000,2867.640000,2875.680000,2871.670000

In [23]:
for data_i in range(len(train_series)):
    Xdf = train_series.iloc[data_i] 
    Xdf = Xdf.dropna()
    Xdf = Xdf.iloc[1:]
    ydf = test_series.iloc[data_i] 
    ydf = ydf.iloc[1:]
    df = pd.concat([Xdf,ydf])
    data = pd.DataFrame({"y": df})
    data.index = np.arange(len(data))
    data = feature_extractor(data)
    print(f"{data_i} shape of new data {data.shape}")
    data.to_csv(f"Dataset/Extracted_M4/{data_i}_M4_{M4_TYPE}.csv")

0 shape of new data (605, 10)
1 shape of new data (1564, 10)
2 shape of new data (605, 10)
3 shape of new data (1605, 10)
4 shape of new data (2244, 10)
5 shape of new data (2558, 10)
6 shape of new data (785, 10)
7 shape of new data (810, 10)
8 shape of new data (1564, 10)
9 shape of new data (1605, 10)
10 shape of new data (1564, 10)
11 shape of new data (682, 10)
12 shape of new data (785, 10)
13 shape of new data (1563, 10)
14 shape of new data (978, 10)
15 shape of new data (1168, 10)
16 shape of new data (1005, 10)
17 shape of new data (895, 10)
18 shape of new data (2244, 10)
19 shape of new data (1563, 10)
20 shape of new data (1272, 10)
21 shape of new data (1048, 10)
22 shape of new data (2244, 10)
23 shape of new data (682, 10)
24 shape of new data (2244, 10)
25 shape of new data (2139, 10)
26 shape of new data (470, 10)
27 shape of new data (1605, 10)
28 shape of new data (605, 10)
29 shape of new data (2244, 10)
30 shape of new data (682, 10)
31 shape of new data (682, 10)
32 shape of new data (1584, 10)
33 shape of new data (785, 10)
34 shape of new data (682, 10)
35 shape of new data (1605, 10)
36 shape of new data (976, 10)
37 shape of new data (1259, 10)
38 shape of new data (1005, 10)
39 shape of new data (785, 10)
40 shape of new data (682, 10)
41 shape of new data (895, 10)
42 shape of new data (2140, 10)
43 shape of new data (1568, 10)
44 shape of new data (2139, 10)
45 shape of new data (2244, 10)
46 shape of new data (1605, 10)
47 shape of new data (1005, 10)
48 shape of new data (682, 10)
49 shape of new data (1605, 10)
50 shape of new data (1671, 10)
51 shape of new data (2139, 10)
52 shape of new data (895, 10)
53 shape of new data (985, 10)
54 shape of new data (1564, 10)
55 shape of new data (1005, 10)
56 shape of new data (2244, 10)
57 shape of new data (785, 10)
58 shape of new data (2244, 10)
59 shape of new data (785, 10)
60 shape of new data (1005, 10)
61 shape of new data (1005, 10)
62 shape of new data (2244, 10)
63 shape of new data (901, 10)
64 shape of new data (682, 10)
65 shape of new data (785, 10)
66 shape of new data (1563, 10)
67 shape of new data (1409, 10)
68 shape of new data (1605, 10)
69 shape of new data (978, 10)
70 shape of new data (1666, 10)
71 shape of new data (2244, 10)
72 shape of new data (1563, 10)
73 shape of new data (895, 10)
74 shape of new data (1005, 10)
75 shape of new data (1605, 10)
76 shape of new data (1563, 10)
77 shape of new data (1605, 10)
78 shape of new data (785, 10)
79 shape of new data (1563, 10)
80 shape of new data (1605, 10)
81 shape of new data (1568, 10)
82 shape of new data (1473, 10)
83 shape of new data (2244, 10)
84 shape of new data (1605, 10)
85 shape of new data (1005, 10)
86 shape of new data (605, 10)
87 shape of new data (1584, 10)
88 shape of new data (1563, 10)
89 shape of new data (1563, 10)
90 shape of new data (1605, 10)
91 shape of new data (1473, 10)
92 shape of new data (967, 10)
93 shape of new data (2244, 10)
94 shape of new data (2244, 10)
95 shape of new data (2244, 10)
96 shape of new data (1005, 10)
97 shape of new data (2139, 10)
98 shape of new data (682, 10)
99 shape of new data (471, 10)
100 shape of new data (1605, 10)
101 shape of new data (1244, 10)
102 shape of new data (1564, 10)
103 shape of new data (682, 10)
104 shape of new data (1564, 10)
105 shape of new data (1564, 10)
106 shape of new data (785, 10)
107 shape of new data (1564, 10)
108 shape of new data (1605, 10)
109 shape of new data (1605, 10)
110 shape of new data (2244, 10)
111 shape of new data (895, 10)
112 shape of new data (1048, 10)
113 shape of new data (895, 10)
114 shape of new data (1563, 10)
115 shape of new data (1563, 10)
116 shape of new data (2244, 10)
117 shape of new data (605, 10)
118 shape of new data (682, 10)
119 shape of new data (2557, 10)
120 shape of new data (2140, 10)
121 shape of new data (785, 10)
122 shape of new data (2244, 10)
123 shape of new data (895, 10)
124 shape of new data (810, 10)
125 shape of new data (1605, 10)
126 shape of new data (1605, 10)
127 shape of new data (901, 10)
128 shape of new data (2244, 10)
129 shape of new data (1005, 10)
130 shape of new data (895, 10)
131 shape of new data (2244, 10)
132 shape of new data (1005, 10)
133 shape of new data (1048, 10)
134 shape of new data (1563, 10)
135 shape of new data (682, 10)
136 shape of new data (895, 10)
137 shape of new data (1168, 10)
138 shape of new data (1605, 10)
139 shape of new data (895, 10)
140 shape of new data (1563, 10)
141 shape of new data (1605, 10)
142 shape of new data (1168, 10)
143 shape of new data (2140, 10)
144 shape of new data (1168, 10)
145 shape of new data (1563, 10)
146 shape of new data (1568, 10)
147 shape of new data (682, 10)
148 shape of new data (682, 10)
149 shape of new data (810, 10)
150 shape of new data (605, 10)
151 shape of new data (1563, 10)
152 shape of new data (1564, 10)
153 shape of new data (785, 10)
154 shape of new data (1005, 10)
155 shape of new data (785, 10)
156 shape of new data (2245, 10)
157 shape of new data (682, 10)
158 shape of new data (895, 10)
159 shape of new data (1564, 10)
160 shape of new data (2140, 10)
161 shape of new data (785, 10)
162 shape of new data (2244, 10)
163 shape of new data (1563, 10)
164 shape of new data (1564, 10)
165 shape of new data (2244, 10)
166 shape of new data (785, 10)
167 shape of new data (901, 10)
168 shape of new data (682, 10)
169 shape of new data (1605, 10)
170 shape of new data (2140, 10)
171 shape of new data (895, 10)
172 shape of new data (1605, 10)
173 shape of new data (1605, 10)
174 shape of new data (622, 10)
175 shape of new data (614, 10)
176 shape of new data (1005, 10)
177 shape of new data (1244, 10)
178 shape of new data (1564, 10)
179 shape of new data (1005, 10)
180 shape of new data (1089, 10)
181 shape of new data (895, 10)
182 shape of new data (895, 10)
183 shape of new data (2244, 10)
184 shape of new data (1605, 10)
185 shape of new data (901, 10)
186 shape of new data (1605, 10)
187 shape of new data (1874, 10)
188 shape of new data (1563, 10)
189 shape of new data (465, 10)
190 shape of new data (682, 10)
191 shape of new data (1473, 10)
192 shape of new data (1605, 10)
193 shape of new data (1563, 10)
194 shape of new data (895, 10)
195 shape of new data (785, 10)
196 shape of new data (895, 10)
197 shape of new data (1835, 10)
198 shape of new data (1584, 10)
199 shape of new data (2139, 10)
200 shape of new data (1563, 10)
201 shape of new data (682, 10)
202 shape of new data (1605, 10)
203 shape of new data (895, 10)
204 shape of new data (1563, 10)
205 shape of new data (2139, 10)
206 shape of new data (785, 10)
207 shape of new data (682, 10)
208 shape of new data (2244, 10)
209 shape of new data (785, 10)
210 shape of new data (895, 10)
211 shape of new data (682, 10)
212 shape of new data (895, 10)
213 shape of new data (1563, 10)
214 shape of new data (785, 10)
215 shape of new data (539, 10)
216 shape of new data (1563, 10)
217 shape of new data (2244, 10)
218 shape of new data (967, 10)
219 shape of new data (2244, 10)
220 shape of new data (1563, 10)
221 shape of new data (1605, 10)
222 shape of new data (1048, 10)
223 shape of new data (1272, 10)
224 shape of new data (978, 10)
225 shape of new data (682, 10)
226 shape of new data (605, 10)
227 shape of new data (785, 10)
228 shape of new data (1168, 10)
229 shape of new data (895, 10)
230 shape of new data (1168, 10)
231 shape of new data (1563, 10)
232 shape of new data (2244, 10)
233 shape of new data (682, 10)
234 shape of new data (1005, 10)
235 shape of new data (1605, 10)
236 shape of new data (1563, 10)
237 shape of new data (1563, 10)
238 shape of new data (1584, 10)
239 shape of new data (1605, 10)
240 shape of new data (2244, 10)
241 shape of new data (986, 10)
242 shape of new data (785, 10)
243 shape of new data (1564, 10)
244 shape of new data (1005, 10)
245 shape of new data (682, 10)
246 shape of new data (1312, 10)
247 shape of new data (2244, 10)
248 shape of new data (1563, 10)
249 shape of new data (2244, 10)
250 shape of new data (785, 10)
251 shape of new data (1254, 10)

In [26]:
deneme = pd.read_csv(f"Dataset/Extracted_M4/{22}_M4_{M4_TYPE}.csv")
deneme

,Unnamed: 0,y,y-1,y-2,y-3,y-4,y-52,y-1_rolling_mean_4,y-1_rolling_std_4,y-1_rolling_mean_7,y-1_rolling_std_7
0,0,827.5550,798.8435,808.0706,800.3789,796.0307,716.1708,800.830925,5.151351,791.626042,9.106614
1,1,811.0204,827.5550,798.8435,808.0706,800.3789,702.4151,808.712000,13.194669,795.569208,13.096952
2,2,813.1888,811.0204,827.5550,798.8435,808.0706,702.4953,811.372375,11.970459,798.333458,12.504132
3,3,801.5011,813.1888,811.0204,827.5550,798.8435,697.5817,812.651925,11.771779,800.823325,12.212073
4,4,802.4190,801.5011,813.1888,811.0204,827.5550,704.2284,813.316325,10.764555,801.825050,11.678411
...,...,...,...,...,...,...,...,...,...,...,...
2239,2239,16027.7390,16042.0990,16092.3280,16086.3420,16056.8110,15636.1640,16069.395000,23.920368,16039.087083,88.377034
2240,2240,16096.7190,16027.7390,16042.0990,16092.3280,16086.3420,15646.2530,16062.127000,32.052675,16026.276333,76.159266
2241,2241,16115.7500,16096.7190,16027.7390,16042.0990,16092.3280,15602.5530,16064.721250,34.954454,16019.875500,65.080192
2242,2242,15955.4880,16115.7500,16096.7190,16027.7390,16042.0990,15584.9490,16070.576750,42.308765,16031.605083,68.832080
2243,2243,15951.6660,15955.4880,16115.7500,16096.7190,16027.7390,15426.2310,16048.924000,72.867841,16034.316583,64.678270

##########################
BURADAN SONRASI DÜZENLENDİ VE ÜSTTEKİ FOR LOOPA ALINDI
##########################

In [125]:
Xdf = train_series.iloc[0] 
Xdf = Xdf.dropna()
Xdf = Xdf.iloc[1:]
Xdf

V2       6169.6
V3       6216.1
V4       6345.7
V5       6147.7
V6       6153.1
          ...
V1427    9448.3
V1428    9329.3
V1429    9399.8
V1430    9509.9
V1431    9563.6
Name: 3469, Length: 1430, dtype: object

In [126]:
ydf = test_series.iloc[0] 
ydf = ydf.iloc[1:]
ydf

V2     9590.2
V3     9565.6
V4     9530.8
V5     9449.5
V6     9173.0
V7     9309.7
V8     9408.5
V9     9505.7
V10    9505.7
V11    9488.9
V12    9398.5
V13    9350.4
V14    9381.2
V15    9402.4
Name: 3469, dtype: object

In [127]:
df = pd.concat([Xdf,ydf])
df

V2     6169.6
V3     6216.1
V4     6345.7
V5     6147.7
V6     6153.1
        ...
V11    9488.9
V12    9398.5
V13    9350.4
V14    9381.2
V15    9402.4
Name: 3469, Length: 1444, dtype: object

In [128]:
data = pd.DataFrame({"y": df})
data.index = np.arange(len(data))
data

           y
0     6169.6
1     6216.1
2     6345.7
3     6147.7
4     6153.1
...      ...
1439  9488.9
1440  9398.5
1441  9350.4
1442  9381.2
1443  9402.4

[1444 rows x 1 columns]

In [129]:
data.loc[:,"y-1"] = data.loc[:,"y"].shift(1)
data.loc[:,"y-2"] = data.loc[:,"y"].shift(2)
data.loc[:,"y-3"] = data.loc[:,"y"].shift(3)
data.loc[:,"y-4"] = data.loc[:,"y"].shift(4)

data.loc[:,"y-7"] = data.loc[:,"y"].shift(7)
data.loc[:,"y-14"] = data.loc[:,"y"].shift(14)
data.loc[:,"y-28"] = data.loc[:,"y"].shift(28)

data

           y     y-1     y-2     y-3     y-4     y-7    y-14    y-28
0     6169.6    None    None    None    None    None    None    None
1     6216.1  6169.6    None    None    None    None    None    None
2     6345.7  6216.1  6169.6    None    None    None    None    None
3     6147.7  6345.7  6216.1  6169.6    None    None    None    None
4     6153.1  6147.7  6345.7  6216.1  6169.6    None    None    None
...      ...     ...     ...     ...     ...     ...     ...     ...
1439  9488.9  9505.7  9505.7  9408.5  9309.7  9530.8  9448.3  9732.5
1440  9398.5  9488.9  9505.7  9505.7  9408.5  9449.5  9329.3  9816.6
1441  9350.4  9398.5  9488.9  9505.7  9505.7  9173.0  9399.8  9741.7
1442  9381.2  9350.4  9398.5  9488.9  9505.7  9309.7  9509.9  9818.4
1443  9402.4  9381.2  9350.4  9398.5  9488.9  9408.5  9563.6  9873.2

[1444 rows x 8 columns]

In [130]:

data.loc[:,"y_rolling_mean_4"] = data.loc[:,"y"].rolling(4).mean()
data.loc[:,"y_rolling_std_4"] = data.loc[:,"y"].rolling(4).std()

data.loc[:,"y_rolling_mean_7"] = data.loc[:,"y"].rolling(7).mean()
data.loc[:,"y_rolling_std_7"] = data.loc[:,"y"].rolling(7).std()

data.loc[:,"y_rolling_mean_14"] = data.loc[:,"y"].rolling(14).mean()
data.loc[:,"y_rolling_std_14"] = data.loc[:,"y"].rolling(14).std()

data.loc[:,"y_rolling_mean_28"] = data.loc[:,"y"].rolling(28).mean()
data.loc[:,"y_rolling_std_28"] = data.loc[:,"y"].rolling(28).std()

In [131]:
data

,y,y-1,y-2,y-3,y-4,y-7,y-14,y-28,y_rolling_mean_4,y_rolling_std_4,y_rolling_mean_7,y_rolling_std_7,y_rolling_mean_14,y_rolling_std_14,y_rolling_mean_28,y_rolling_std_28
0,6169.6,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6216.1,6169.6,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6345.7,6216.1,6169.6,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6147.7,6345.7,6216.1,6169.6,None,None,None,None,6219.775,88.662182,NaN,NaN,NaN,NaN,NaN,NaN
4,6153.1,6147.7,6345.7,6216.1,6169.6,None,None,None,6215.650,92.092182,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1439,9488.9,9505.7,9505.7,9408.5,9309.7,9530.8,9448.3,9732.5,9477.200,46.479673,9405.857143,123.971527,9452.157143,117.315542,9615.192857,204.984435
1440,9398.5,9488.9,9505.7,9505.7,9408.5,9449.5,9329.3,9816.6,9474.700,51.413617,9398.571429,122.468700,9457.100000,113.123942,9600.260714,204.997789
1441,9350.4,9398.5,9488.9,9505.7,9505.7,9173.0,9399.8,9741.7,9435.875,73.914472,9423.914286,78.457726,9453.571429,115.787813,9586.285714,208.309547
1442,9381.2,9350.4,9398.5,9488.9,9505.7,9309.7,9509.9,9818.4,9404.750,59.522573,9434.128571,64.527739,9444.378571,116.080285,9570.671429,206.645515
1443,9402.4,9381.2,9350.4,9398.5,9488.9,9408.5,9563.6,9873.2,9383.125,23.682254,9433.257143,64.971195,9432.864286,111.238680,9553.857143,200.170254

In [132]:
data = data.dropna()
data

,y,y-1,y-2,y-3,y-4,y-7,y-14,y-28,y_rolling_mean_4,y_rolling_std_4,y_rolling_mean_7,y_rolling_std_7,y_rolling_mean_14,y_rolling_std_14,y_rolling_mean_28,y_rolling_std_28
28,6040.5,6007.1,6044.1,6211.2,6255.3,6178.0,6059.5,6169.6,6075.725,91.840092,6131.057143,98.440775,6101.257143,93.554975,6100.735714,92.513988
29,5973.1,6040.5,6007.1,6044.1,6211.2,6164.7,5935.7,6216.1,6016.200,33.213050,6103.685714,113.076500,6103.928571,88.881126,6092.057143,92.688584
30,5817.4,5973.1,6040.5,6007.1,6044.1,6194.5,6023.5,6345.7,5959.525,98.664630,6049.814286,147.261179,6089.207143,116.121253,6073.189286,92.914865
31,5690.4,5817.4,5973.1,6040.5,6007.1,6255.3,6031.3,6147.7,5880.350,157.368241,5969.114286,169.057164,6064.857143,157.550205,6056.857143,116.524159
32,5640.2,5690.4,5817.4,5973.1,6040.5,6211.2,6053.3,6153.1,5780.275,148.613893,5887.542857,170.530436,6035.350000,194.283218,6038.539286,138.984146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1439,9488.9,9505.7,9505.7,9408.5,9309.7,9530.8,9448.3,9732.5,9477.200,46.479673,9405.857143,123.971527,9452.157143,117.315542,9615.192857,204.984435
1440,9398.5,9488.9,9505.7,9505.7,9408.5,9449.5,9329.3,9816.6,9474.700,51.413617,9398.571429,122.468700,9457.100000,113.123942,9600.260714,204.997789
1441,9350.4,9398.5,9488.9,9505.7,9505.7,9173.0,9399.8,9741.7,9435.875,73.914472,9423.914286,78.457726,9453.571429,115.787813,9586.285714,208.309547
1442,9381.2,9350.4,9398.5,9488.9,9505.7,9309.7,9509.9,9818.4,9404.750,59.522573,9434.128571,64.527739,9444.378571,116.080285,9570.671429,206.645515
1443,9402.4,9381.2,9350.4,9398.5,9488.9,9408.5,9563.6,9873.2,9383.125,23.682254,9433.257143,64.971195,9432.864286,111.238680,9553.857143,200.170254

In [133]:
data.index = np.arange(len(data))

In [ ]:
data.to_csv(f"{data_i}_M4.csv")